name: 🐞 Bug Report
description: If something isn't working as expected 🤔
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: What happened?
      description: A concise description of what you're experiencing.
      placeholder: |
        A clear and concise description of the problem...
        A good bug report shouldn't leave others needing to chase you up for more information.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior or Solution
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Such as details about the system where you're using this package.

        Example of environment detail:
        - Version of this package: *e.g. 1.0.0, 1.0.1, 1.1.0*
        - PHP version: *e.g. 7.3.16, 7.4.4*
        - OS: *e.g. Windows 10, Linux (Ubuntu 18.04.1), macOS Catalina (10.15.3)*

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
     required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/divineniiquaye/rade-di/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
